
create table IF NOT EXISTS　users
(
   id integer generated by default as identity,
   name varchar (255),
   password varchar (255),
   mail varchar (255),
   create_datetime timestamp not null,
   primary key (id)
);